create TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL CHECK (name <> ''),
    description VARCHAR(200),
    releaseDate DATE,
    duration INT CHECK (duration > 0)
);

create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL CHECK (login <> ''),
    name VARCHAR(200),
    birthday DATE
);

create TABLE IF NOT EXISTS friends_status (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS friends (
    senderUser_id BIGINT REFERENCES users(id) ON delete CASCADE,
    receiverUser_id BIGINT REFERENCES users(id) ON delete CASCADE,
    status INT REFERENCES friends_status(id),
    PRIMARY KEY (senderUser_id, receiverUser_id)
);

create TABLE IF NOT EXISTS films_likes (
    films_id BIGINT REFERENCES films(id) ON delete CASCADE,
    users_id BIGINT REFERENCES users(id) ON delete CASCADE,
    PRIMARY KEY (films_id, users_id)
);

create TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS films_genre (
    films_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genre(id),
    PRIMARY KEY (films_id, genre_id)
);
create TABLE IF NOT EXISTS rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS films_rating (
    films_id BIGINT REFERENCES films(id) ON delete CASCADE,
    rating_id BIGINT REFERENCES rating(id),
    PRIMARY KEY (films_id, rating_id)
);

CREATE TABLE IF NOT EXISTS director (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_director (
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    director_id BIGINT REFERENCES director(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);