DROP TABLE IF EXISTS film_director CASCADE;
DROP TABLE IF EXISTS director CASCADE;
DROP TABLE IF EXISTS films_rating CASCADE;
DROP TABLE IF EXISTS films_genre CASCADE;
DROP TABLE IF EXISTS films_likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS friends_status CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS rating CASCADE;

create TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    rating_id BIGINT REFERENCES rating(id)
);

create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE
);

create TABLE IF NOT EXISTS friends_status (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS friends (
    senderUser_id BIGINT REFERENCES users(id) ON delete CASCADE,
    receiverUser_id BIGINT REFERENCES users(id) ON delete CASCADE,
    status INT REFERENCES friends_status(id),
    PRIMARY KEY (senderUser_id, receiverUser_id)
);

create TABLE IF NOT EXISTS films_likes (
    films_id BIGINT REFERENCES films(id) ON delete CASCADE,
    users_id BIGINT REFERENCES users(id) ON delete CASCADE,
    PRIMARY KEY (films_id, users_id)
);

create TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS films_genre (
    films_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    genre_id BIGINT REFERENCES genre(id),
    PRIMARY KEY (films_id, genre_id)
);
create TABLE IF NOT EXISTS rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS films_rating (
    films_id BIGINT REFERENCES films(id) ON delete CASCADE,
    rating_id BIGINT REFERENCES rating(id),
    PRIMARY KEY (films_id, rating_id)
);

CREATE TABLE IF NOT EXISTS director (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_director (
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    director_id BIGINT REFERENCES director(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);
