name: Films API Tests

on:
  pull_request_target:  # Вместо pull_request - разрешает PR из форков
    branches: [ develop ]

jobs:
  build:
    uses: yandex-praktikum/java-filmorate/.github/workflows/api-tests.yml@ci